### ISSUE TITLE
Create Button

### ISSUE THREAD

**Issue by Hedg0305** [juathanduarte/blablaCampus#6]
![Image](https://github.com/juathanduarte/blablaCampus/assets/61093997/61c56a5a-0808-4195-8410-3448f1d4bbf2)

![Image](https://github.com/juathanduarte/blablaCampus/assets/61093997/7e185851-99f0-46c2-a330-c528a614eb92)

![Image](https://github.com/juathanduarte/blablaCampus/assets/61093997/528487cf-34a4-4fb1-badf-6c14f3293c7c)

![Image](https://github.com/juathanduarte/blablaCampus/assets/61093997/755a958c-c4eb-428c-a676-34bca04b5322)

**Comment by juathanduarte** [comment]
- Botão de entrar [OK]

**Comment by juathanduarte** [comment]
- Botão de bloquear/desbloquear, utilizando estado [OK]
